// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbhlAjGgeZVnmAo-Cd_MVjAZ1UxW1oyuE',
    appId: '1:14964769981:web:259fe8883199b2d315e3d4',
    messagingSenderId: '14964769981',
    projectId: 'oiot-mobile',
    authDomain: 'oiot-mobile.firebaseapp.com',
    storageBucket: 'oiot-mobile.appspot.com',
    measurementId: 'G-E1J4KEM8L7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfxO0p1dCP60od5vg1YpYZXR9r61KkyUo',
    appId: '1:14964769981:android:d276b8e7d67f1a9515e3d4',
    messagingSenderId: '14964769981',
    projectId: 'oiot-mobile',
    storageBucket: 'oiot-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxrYsDYSJyQlB036onfzq0X_JQCQd6uJs',
    appId: '1:14964769981:ios:d497b11eb09023f815e3d4',
    messagingSenderId: '14964769981',
    projectId: 'oiot-mobile',
    storageBucket: 'oiot-mobile.appspot.com',
    iosBundleId: 'com.oiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxrYsDYSJyQlB036onfzq0X_JQCQd6uJs',
    appId: '1:14964769981:ios:d497b11eb09023f815e3d4',
    messagingSenderId: '14964769981',
    projectId: 'oiot-mobile',
    storageBucket: 'oiot-mobile.appspot.com',
    iosBundleId: 'com.oiot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbhlAjGgeZVnmAo-Cd_MVjAZ1UxW1oyuE',
    appId: '1:14964769981:web:eae2a10724802dc715e3d4',
    messagingSenderId: '14964769981',
    projectId: 'oiot-mobile',
    authDomain: 'oiot-mobile.firebaseapp.com',
    storageBucket: 'oiot-mobile.appspot.com',
    measurementId: 'G-Z0MR4V7JR2',
  );
}
